aio-libs/aioredis-py

- aioredis/commands/sorted_set.py
- tests/sorted_set_commands_test.py
parameter order was wrong. Must be 'ZREVRANGEBYSCORE key max min'
ref : http://redis.io/commands/zrevrangebyscore
> zrevrangebyscore command fix

- aioredis/connection.py
- tests/pool_test.py
At present, Even if create_pool has an encoding, Inevitably, we should write the code for decoding the result of hgetall.
fix about it
> fix : when create_pool has an encoding, hgetall has to return decoding results

- aioredis/connection.py
- aioredis/util.py
Without this, Channel#wait_message() doesn't return nor raise any exceptions when the connection is lost.
> Close all pubsub channels when connection is closed

- aioredis/commands/server.py
- tests/server_commands_test.py
API changes:
* `config_get()` `parameter` defaults to `'*'`
* `slaveof()` deprecated in favour of `slaveof(None)`
* `role()` response parsing implemented (returns named tuples)
> Server commands tests

- aioredis/commands/__init__.py
- aioredis/connection.py
- aioredis/pool.py
- docs/api_reference.rst
[By design](http://redis.io/topics/security), Redis doesn't natively support encryption via SSL/TLS. However, it can be added with an SSL proxy. 
For this reason, [some popular Redis libraries support SSL connections](https://github.com/andymccurdy/redis-py/blob/1c2071762ad9b9288e786665990083e61c1cf355/redis/connection.py#L656).
This change adds support for SSL/TLS by leveraging asyncio's existing SSL support in [asyncio.BaseEventLoop.create_connection](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.BaseEventLoop.create_connection) and using its semantics.
I didn't exhaustively research or test this change, so this pull request is simply my first pass at how such a change might look. I welcome critical feedback on it.
Thanks for this library!
> Added support for SSL/TLS

- aioredis/connection.py
- tests/connection_test.py
Otherwise, if an 'await connection.wait_closed()' is cancelled, the _close_waiter will be cancelled, too. This raises an error, because when _read_task is done, it tries to set the result of the already cancelled _close_waiter.
> Bugfix: Shield close_waiter from cancellation of wait_closed.

- aioredis/commands/hash.py
- aioredis/util.py
- tests/hash_commands_test.py
> Extended HMSET

- aioredis/pool.py
- tests/pool_test.py
This patch closes the RedisPool when the connection to the redis server has failed. We would get an asyncio error when closing the event loop:
```
Task was destroyed but it is pending!
task: <Task pending coro=<RedisPool._do_close() running at python3.5/site-packages/aioredis/pool.py:102> wait_for=<Future pending cb=[Task._wakeup()]>>
```
> Close RedisPool when connection to the redis server has failed (To prevent asyncio lock)

- aioredis/commands/server.py
- tests/server_commands_test.py
Set a default param value of `'default'` (same as how redis-cli works http://redis.io/commands/INFO) for the `info()` command. Also added validation for the section param of the same command.
> Set default and validate section for info cmd

- aioredis/commands/generic.py
- aioredis/commands/server.py
- tests/generic_commands_test.py
Add shortcut command `migrate_keys` for `MIGRATE…KEYS key1 [key2 ...]` command.
Also fixed `debug_sleep`.
> add migrate_keys command

- aioredis/pool.py
Pool creating using deprecated _commands_factory_ argument fails with the following error:
`AttributeError: module 'warnings' has no attribute 'DeprecationWarning'`
> Fix raising of deprecation warning

- aioredis/pubsub.py
- aioredis/util.py
Starting with Python 3.5.2 the coroutine `__aiter__` functions will throw PendingDeprecationWarnings. Starting with Python 3.6 it will be actual DeprecationWarnings.
See https://www.python.org/dev/peps/pep-0492/#api-design-and-implementation-revisions
> Avoid deprecation warnings due to legacy __aiter__ protocol.

- aioredis/commands/sorted_set.py
- tests/sorted_set_commands_test.py
Added the `ZREVRANGEBYLEX` command and tests. Closes #200.
> Added ZREVRANGEBYLEX command

- aioredis/commands/__init__.py
- tests/connection_test.py
https://github.com/aio-libs/aiohttp-session/blob/fe21ec8a68e8b1030dade1a363f9c0da6495ad1c/aiohttp_session/redis_storage.py#L28
> backward compatability with `yield from as conn`

- aioredis/pubsub.py
- tests/pubsub_receiver_test.py
- tests/py35_pubsub_receiver_test.py
This fixes the case when pubsub receiver is blocked in `get()` and then `stop()` is called,
see test for details.
> Pub/Sub Receiver stop() fix

- aioredis/pool.py
- tests/pool_test.py
A redis connection cannot return to a pool if it has pending requests, especially blocking commands like "BLPOP/BRPOP". The command may block for an indefinite time, and stops the following commands from executing if the connection is acquired from the pool. Also, because the command is still executing, the BRPOP command may pop an item and drop it which creates bugs which are very hard to debug.
> Do not return a connection with pending requests to the pool

- CONTRIBUTORS.txt
- aioredis/connection.py
- aioredis/pool.py
- docs/api_reference.rst
- tests/connection_test.py
- tests/pool_test.py
Related to #184, it allows aioredis to configure a limited
time that will be used trying to open a connection if it is
reached an `asyncio.TimeoutError` will be raised
By default, any timeout is configured.
Not very happy with the current test implementation, at integration level there is not an easy way to test it, if you come with something better please ping me.
> Support for connection timeout param

- aioredis/commands/transaction.py
- tests/transaction_commands_test.py
This fixes the issue when using redis pool and executing 'slow' mutli-exec command:
pool-owned connection was getting released back to pool before result of `exec` was received.
> Fix for multi-exec transaction cancelled error

- aioredis/connection.py
- aioredis/pool.py
- tests/connection_test.py
- tests/pool_test.py
Both factories to create a new pool and new connections allow to the
developer pass as a kw an alternative class. Developers can develop
their own pools or connection classes inheriting from the official one
and implementing ad-hoc functionalities.
> Allow inject a pool class and connection class

- aioredis/locks.py
- aioredis/pool.py
- tests/locks_test.py
Copied and adapted code from the PR pending to be merged yet [1]
[1] https://github.com/python/cpython/pull/1031
> #231 Patch for the cpython issue with Lock bpo-27585

- aioredis/locks.py
@popravich it should be merged ASAP, sorry fo the bug introduced plus no detection in the UT. I will do another MR to have support for Python 3.6.2, using the Python implementation.
We detected that issue together with @argaen when the new Python RC was tested with aiocache.
We have been running our system with that version since it was published, we didn't notice any particular issue. I guess that having a pool overallocated of opened connections has hide that mistake.
> Fix critical bug with patched Lock

- .travis.yml
v5.8.0 has a bug (related to C python extension, see  https://bitbucket.org/pypy/pypy/issues/2592/pypy3-listpop-returns-none-for-a-list), so update to v5.9.0 (ie, nightly build)
> update PyPy3 to nightly build (>v5.8.0)

- aioredis/connection.py
- tests/pubsub_commands_test.py
Fixes https://github.com/aio-libs/aioredis/issues/249
> Support PING in pubsub mode

- aioredis/connection.py
- aioredis/stream.py
- tests/conftest.py
- tests/connection_test.py
- tests/pool_test.py
- tests/stream_test.py
- tests/transaction_commands_test.py
The connection opened with the server uses a customized StreamReader
that get rid of the double buffering between the operating system and
the Redis parser. This also allows _aioredis_ to get rid of a current bug
with abruptly terminated connections.
Current implementation does not allow to keep giving support with
pause/resume the transport if some watermark has been overflowed,
the current implementation of hiredis does not publish the length of the
buffer.
Worth mentioning that doing a micro benchmark [1] the performance gains
observed is a 5%. This has been tested only with the default Asyncio loop. IMHO will worth it a discussion if a _cython_ implementation will help for environments with _uvloop_ ( I think so ).
[1] https://gist.github.com/pfreixes/e320b6f398aa7644c19188ccf2f443b1
> Use a custom StreamrReader #271

- aioredis/connection.py
> Use call_soon() when closing in conn._read_data()

- aioredis/commands/sorted_set.py
- tests/sorted_set_commands_test.py
Added `exist` parameter to the `zadd` method as ability setup NX or XX argument.
> Added 'exist' param to the 'zadd' method as ability setup NX or XX argument

- setup.py
SO the list of supported Python versions displayed on PyPI includes 3.6.
Closes #312
> Add missing classifier for Python 3.6

- aioredis/commands/transaction.py
- aioredis/connection.py
- aioredis/errors.py
- tests/connection_commands_test.py
- tests/integrational_test.py
- tests/transaction_commands_test.py
Cancel pending futures with one of distinct errors (`ConnectionClosedError`, 
`ConnectionForcedCloseError` or builtin exception like `ConnectionError`)
instead of calling `cancel()` method.
> Distinct error for futures cancellation

- aioredis/__init__.py
- aioredis/connection.py
- aioredis/errors.py
- aioredis/pool.py
- tests/connection_test.py
- tests/errors_test.py
- tests/pool_test.py
- tests/transaction_commands_test.py
Rebased #262;
Resolves #186 and #262 ;
> Support maxclients error #186

- .gitignore
- aioredis/errors.py
- aioredis/sentinel/pool.py
- tests/conftest.py
- tests/errors_test.py
- tests/sentinel_commands_test.py
Rebased from master;
Use more specific error kind.
> #284 Correct error message on sentinel discovery of master/slave with password

- aioredis/commands/sorted_set.py
- docs/migration.rst
- tests/sorted_set_commands_test.py
Amend sorted set commands to return pairs instead of plain list when `withscores` argument is set to True (resolves #209)
> Update sorted set commands to return list[tuple] instead of plain list.

- aioredis/commands/hash.py
- aioredis/util.py
- docs/migration.rst
- tests/hash_commands_test.py
It was returning plain list of keys and values (`['field-1', 'value-1', 'field-2', 'value-2']`)
Now: `[('field-1', 'value-1'), ('field-2', 'value-2')]`
Similar to #334
> Update hscan command to return list of tuples

- aioredis/stream.py
- tests/conftest.py
- tests/connection_test.py
- tests/pool_test.py
* Fix "max clients" tests — uvloop closes connection earlier and so `ConnectionClosedError` is raised;
* Fix aioredis.StreamReader to buffer data until `set_parser` is called — uvloop reads and calls `feed_data` earlier than asyncio loop.
> few fixes related to uvloop

- aioredis/pool.py
pool module ConnectionsPool class get method annotation has error
```python
def get(self):
'''Return async context manager for working with connection.
async with pool.get() as conn:
await conn.get(key)
'''
return _AsyncConnectionContextManager(self)
```
Run the following code will raise exception.
```python
import asyncio
import aioredis
loop = asyncio.get_event_loop()
async def go():
pool = await aioredis.create_pool(
'redis://localhost',
minsize=5, maxsize=10,
loop=loop)
async with pool.get() as conn:
await conn.get('key')
pool.close()
await pool.wait_closed()
loop.run_until_complete(go())
```
```bash
AttributeError: 'RedisConnection' object has no attribute 'get'
```
> fix connections pool get method annotation

- aioredis/abc.py
- aioredis/connection.py
- aioredis/pubsub.py
- docs/api_reference.rst
- docs/mpsc.rst
- examples/pubsub2.py
- tests/pubsub_commands_test.py
- tests/pubsub_receiver_test.py
> Pubsub receiver hang fix

- aioredis/pool.py
- tests/sentinel_commands_test.py
Fix issue with Sentinel client and ConnectionsPool causing endless reconnect on service discovery.
`ConnectionsPool._fill_free` was always calling `ManagedPool._create_new_connection` with `_NON_DISCOVERED` address marker causing `ManagedPool` to clear all currently established connections.
So setting `minsize` value greater then 1 was putting  `_fill_free` in endless loop.
> Sentinel discovery fix

- docs/api_reference.rst
> fixes #388 - Added password redis_uri example to api_reference

- aioredis/util.py
```
import time
_converters = {
bytes: lambda val: val,
bytearray: lambda val: val,
str: lambda val: val.encode(),
int: lambda val: b'%d' % val,
float: lambda val: b'%r' % val,
}
def encode_command(*args):
"""Encodes arguments into redis bulk-strings array.
Raises TypeError if any of args not of bytearray, bytes, float, int, or str
type.
"""
buf = bytearray(b'*%d\r\n' % len(args))
try:
for arg in args:
barg = _converters[type(arg)](arg)
buf.extend(b'$%d\r\n%s\r\n' % (len(barg), barg))
except:
raise TypeError("Argument {!r} expected to be of bytearray, bytes,"
" float, int, or str type".format(arg))
return buf
_converters_old = {
bytes: lambda val: val,
bytearray: lambda val: val,
str: lambda val: val.encode('utf-8'),
int: lambda val: str(val).encode('utf-8'),
float: lambda val: …
```
> reduce encode_command cost about 60%+

- aioredis/commands/server.py
Nothing prevents the server from returning values that contain a colon.
> Fix INFO parsing

- .appveyor.yml
- .travis.yml
- aioredis/pool.py
- setup.py
- tests/pool_test.py
> Python 3.7

- tests/server_commands_test.py
The tests on master are failing.  See eg. https://travis-ci.com/michael-k/aioredis/builds/84230401
I do not know enough about the redis internals to explain why this change is necessary, but it fixes the tests and the same adjustment was done in redis' test suite.
See https://github.com/antirez/redis/blob/5.0-rc5/00-RELEASENOTES#L191-L193 and https://github.com/antirez/redis/commit/1203a04f5e6b7fe78162080e3ebf32ee71329785
> Adjust tests for redis 5

- aioredis/pool.py
`ConnectionsPool._drop_closed` does not really drop all closed connections. One can see the flaw in the algorithm by running the following simplified example:
```python
from collections import deque
def drop_closed(q):
for i in range(len(q)):
if q[0] == 'C':
q.popleft()
else:
q.rotate(1)
q = deque(['O', 'C', 'C'])
drop_closed(q)
print(q)
```
This patch (hopefully) fixes this problem.
> bug in _drop_closed

- aioredis/commands/transaction.py
- aioredis/connection.py
- aioredis/util.py
- tests/multi_exec_test.py
- tests/transaction_commands_test.py
This fixes #464.
Add `RedisConnection._buffered` context manager (private API) which enables
buffering of encoded commands inside connection and then send it on exit.
The issue and fix has shown several more points that must be fixed or can be enhanced:
* *(enhancement)* `Pipeline` and `MultiExec` classes can be simplified — no need in `_RedisBuffer` and `__getattr__` magic;
* *(enhancement)* proper `discard` for multi/exec transaction can be implemented;
* *(enhancement)* `_buffered` can be exposed through some public API;
* **fix** `watch` + `multi_exec` may not work: `watch` can be sent through one connection in the pool and
`multi/exec` through other; the fix could probably break public API;
> Write buffering

- aioredis/connection.py
- aioredis/pool.py
- aioredis/sentinel/pool.py
- aioredis/util.py
- tests/pool_test.py
When calling `ConnectionsPool.close()` method `_do_close` task is scheduled and stored in
`_close_waiter` attribute which is then awaited in `wait_closed()` method.
Somehow this was causing `_do_close` to stuck in envent loop `asyncio.Taks.all_tasks` in status `finished`.
Fixes #496
> Fix slow memory leak in `wait_closed` implementation

- aioredis/commands/sorted_set.py
- tests/sorted_set_commands_test.py
Available since Redis server 5.0.0.
https://redis.io/commands/zpopmax
https://redis.io/commands/zpopmin
> Add support for `zpopmax` and `zpopmin` redis commands (server 5.0.0+)

- docs/migration.rst
Less rage more range. Not sure what else to say here :)
> Correct `zrage` typo in migration docs

- aioredis/errors.py
Didn't add tests since this case already covered in `tests/connection_commands_test.py:test_auth`
> Add _invalid password_ to AuthError error matches

- .travis.yml
- CONTRIBUTORS.txt
- Makefile
- aioredis/errors.py
- aioredis/parser.py
- tests/requirements.txt
+ Enabls type hints using `mypy`
+ Adds initial type checks for `errors.py` and `parser.py`
None
#555
* Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`
> Type Hints for aioredis

- .github/PULL_REQUEST_TEMPLATE.md
Add aioredis-specific PR template, that includes CONTRIBUTORS.txt
Related to proposed PR for removing CONTRIBUTORS.txt from the global PR template
https://github.com/aio-libs/.github/pull/3
> Add project specific PR template, including CONTRIBUTORS.txt

- CHANGES/605.bugfix
- aioredis/commands/streams.py
- tests/stream_commands_test.py
aioredis will now ignore streams messages which have a `(null)` value for the fields. An example of such a response from Redis:
```
XREADGROUP GROUP fp.sales-store_stock_level_in_cache web-5689899cfc-bsgsl STREAMS production.statistics.*:stream 0
1) 1) "production.statistics.*:stream"
2)  1) 1) "1559345885072-0"
2) (nil)
```
I could only recreate this behaviour using `XREADGROUP`, not `XREAD`. Furthermore, Redis reported there were no messages matching this message ID:
```
XRANGE production.statistics.*:stream 1559345885072-0 1559345885072-0
(empty list or set)
```
No. It is not possible for the user to create a steam message containing no fields.
* name it `<issue_id>.<type>` (e.g. …
> Handling case where redis returns phantom stream messages with no fields

- CHANGES/618.feature
- CONTRIBUTORS.txt
- aioredis/commands/sorted_set.py
- tests/sorted_set_commands_test.py
Implementation of the blocking pop commands for the sorted set: `BZPOPMAX` and `BZPOPMIN`.
Implementation of the the `CH` and `INCR` options of the `ZADD` command.
`Fix issue with …
> Implementation of the BZPOPMAX/BZPOPMIN commands and additional options of ZADD.

- CHANGES/625.feature
- CONTRIBUTORS.txt
- aioredis/commands/streams.py
- tests/stream_commands_test.py
adding noack param to xreadgroup command
> add noack to xreadgroup command

- CHANGES/646.misc
- aioredis/abc.py
- aioredis/locks.py
- aioredis/pool.py
- aioredis/sentinel/pool.py
- setup.py
Fix LGTM.com alerts https://lgtm.com/projects/g/aio-libs/aioredis/alerts/?mode=list
no
> Fix LGTM.com alerts

- CHANGES/648.misc
- CONTRIBUTORS.txt
- aioredis/abc.py
- aioredis/locks.py
- tests/pool_test.py
Fixed: 
```
DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
```
This should not be a problem if the user is using Python 3.5 or later.
"@coroutine" decorator is deprecated since Python 3.8 #648
* Make sure to use full …
> Change "@asyncio.coroutine" to "async def" due to warning in Python 3.8

- CHANGES/657.bugfix
- CONTRIBUTORS.txt
- aioredis/connection.py
- tests/transaction_commands_test.py
Fix incorrect transaction data decoding.
Transaction data always decoded two times if connection encoding was defined and impossible to override connection encoding per transaction command:
Test case:
```python
@pytest.mark.run_loop
async def test_global_encoding(redis, create_redis, server, loop):
redis = await create_redis(
server.tcp_address,
loop=loop, encoding='utf-8')
res = await redis.set('key', 'value')
assert res is True
res = await redis.hmset(
'hash-key', 'foo', 'val1', 'bar', 'val2')
assert res is True
tr = redis.multi_exec()
fut1 = tr.get('key')
fut2 = tr.get('key', encoding='utf-8')
fut3 = tr.get('key', encoding=None)
fut4 = tr.hgetall('hash-key', encoding='utf-8')
await tr.execute()
res = await fut1
assert res == 'value'
res = await fut2
assert res == 'value'
res = await …
```
> Fix transaction data decoding

- aioredis/pool.py
Just a minor fix to remove a duplicate function call I have found while I'm reading the code.
There should be nothing.
This code path is only taken when there are exceptions while creating a new Redis pool, which would rarely happen in normal use cases.
If this is an intended duplication, I think the authors should add a comment describing why.
This is just a simple one-liner PR. :wink:
* `.removal`: …
> Fix duplicate calls to pool.wait_closed() upon create_pool() exception

- .github/dependabot.yml
- .pyup.yml
FYI.
I've dropped pyup (deleted the `/.pyup.yml` and unregistered the project on the pyup.io)
Dependabot is a native tool that is a part of GitHub now. 
I love dependabot, it allows rebuilding PRs created by the bot by `@dependabot recreate` and much more.
There are two dependabots actually: *preview* as it was on the moment of acquisition by GitHub and the *native*.
The *native* still has no *automerge* facility but @mjpieters it is solvable by an additional workflow that approves and merges dependabot's PRs if all checks are passed.
We can add this workflow later.
> Replace pyup with Dependabot github native

- aioredis/commands/sorted_set.py
Fixes docstring mistypes in "zrevrangebylex"
No
> Fix docstring mistype in "zrevrangebylex"

- README.rst
Add a small example in the README showing usage of a single `pool` from multiple coroutines.
In the current README, it is not obvious for someone new to async io that the connection should only be closed once from the top-level caller.
> Add demo of sharing pool from multiple coroutines

- CHANGES/723.bugfix
- aioredis/commands/streams.py
- tests/stream_commands_test.py
I was the original author of this change some time ago (#605), and I now think it is a mistake. If redis decides to return `nil` values then I don't think `aioredis` should eat them.
In my case I am receiving `nil` values when performing an `XCLAIM`. Why does this happen? I'm not sure*, but I know that I definitely want to be able to `ACK` these `nil` messages in order to stop my consumer continually reclaiming them.
Removing of `nil` values by `aioredis` means the response I get looks like, "you could not claim this message," not the more accurate, "you claimed this message but there is no body".
* Perhaps they have been trimmed from the end of the stream but redis still sees them as claimed, so just returns `nil` rather than the message body.
Note that for now I am [monkey patching …
> Stop removing `nil` messages in stream responses

- tests/connection_test.py
Increased the delay in the unit test `test_connection_idle_close` by 3x. This is to give it a larger margin of error when running on Travis CI, as this test seems to fail arbitrarily when redis has not yet timed out by the time the delay is finished.
Relevant section from redis docs:
>Timeouts are not to be considered very precise: Redis avoids to set timer events or to run O(N) algorithms in order to check idle clients, so the check is performed incrementally from time to time. This means that it is possible that while the timeout is set to 10 seconds, the client connection will be closed, for instance, after 12 seconds if many clients are connected at the same time.
https://redis.io/topics/clients
I am not sure if this will definitely fix this issue, but i have made this pr to start the …
> Increase delay in idle timeout unit test in an attempt to prevent it from failing on Travis CI

- CHANGES/726.bugfix
- CONTRIBUTORS.txt
- aioredis/locks.py
#726 fix a problem lead by python3.8
nope
#726 
> fix NoneType object is not iterable when iterate over self._waiters

- CHANGES.txt
- CHANGES/705.bugfix
- CHANGES/705.removal
- aioredis/commands/hash.py
- tests/hash_commands_test.py
This PR add in support to `hset()` to handle multiple field/value pairs, as redis 4.0.0 onwards `HSET` allows for multiple field/value pairs. In addition, `hmset()` and `hmset_dict()` are now deprecated.
I have followed the same convention as [redis-py](https://github.com/andymccurdy/redis-py/) and used the `mapping` keyword argument, I am happy to change it if needed.
redis docs reference:
`As of Redis 4.0.0, HSET is variadic and allows for multiple field/value pairs.`
https://redis.io/commands/hset
`As per Redis 4.0.0, HMSET is considered deprecated. Please use HSET in new code.`
https://redis.io/commands/hmset
pytest and flake8 tests passed locally.
The api doesn't change for existing users, this only adds in additional support while keeping the previous methods working.
Also, calls to …
> Add support for multiple field/value pairs to hset(), Fixes #705

- aioredis/sentinel/pool.py
Removes asyncio.wait usage in aioredis.sentinel.pool
(Please wait for some kind of CI to output)
Edit: I probably want to be on an IDE to make some of these changes and test them beforehand...
No
Fixes #789
* Make sure to use full sentences with correct case and …
> Fix asyncio.wait deprecation warning

- CHANGES/784.feature
- CONTRIBUTORS.txt
- aioredis/commands/sorted_set.py
- tests/sorted_set_commands_test.py
This fixes #784 and eliminates the ambiguity where "-" could mean either
"from the beginning" or "from the literal string -". It is a breaking
API change.
Yes. Users will need to prefix the `min` and `max` value with `[` or `(`.
#784 
* Make sure to use full sentences …
> Change Z*LEX APIs to pass min and max straight through

- CHANGES/855.feature
- CONTRIBUTORS.txt
- aioredis/commands/generic.py
- tests/generic_commands_test.py
Adds support for passing TYPE argument to the SCAN command.
#855
> Add support for TYPE argument of the SCAN command.

- README.rst
- docs/api_reference.rst
- docs/devel.rst
- docs/index.rst
9ab5f3f removed Python 3.5 support, but various bits of documentation
still said Python 3.5 was the minimum version.
No.
#824 
N/A. No code changes, and the CHANGES update is already done by #824.
> Remove references to Python 3.5 from the docs

- .github/workflows/pre-commit-autoupdate.yml
Adds pre-commit autoupdate GitHub action. Taken from cookiecutter-django: * Taken from https://github.com/pydanny/cookiecutter-django/blob/master/.github/workflows/pre-commit-autoupdate.yml
If you would like automerge as well, then you would need another step that can take advantage of GitHub API from within the action.
No
#822 
* `.misc`: …
> Add pre-commit autoupdate action

- CHANGES/876.bugfix
- CONTRIBUTORS.txt
- aioredis/pool.py
- tests/pool_test.py
Fixes hanging pool after pubsub connections died many times (more than pool size)
no
None
> Fixed hanging pool when pubsub connection died

- CHANGES/899.doc
- aioredis/pubsub.py
I've just spend some time scratching my head over this, I initially assumed from the example that `mpsc.pattern()` automatically added the `*`.
no
no
`Fix issue with non-ascii contents in …
> fix pubsub pattern subscribe example

- aioredis/connection.py
Async timeout should be properly awaited.
This should fix a bug
Fixes #923 
> Fix async_timeout not awaited (Fixes #923)

- aioredis/connection.py
- tests/conftest.py
- tests/test_multiprocessing.py
- tests/test_sentinel.py
This prevents a leaked coroutine when the Connection is garbage-collected.
No
resolves #923 
> Use pre-spawned disconnect coro in Connection.__del__

- .github/workflows/ci.yml
Disables the combination of uvloop with Python 3.6 due to https://github.com/MagicStack/uvloop/blob/c808a663b297bb2aee745523c277d6fafecebbeb/setup.py#L5
For some reason, the tests continue, but this should be an error. This was due to the GitHub action at https://github.com/aio-libs/aioredis-py/actions/runs/677918070 but it doesn't explain why everything runs for > 15 minutes
No
No
> Disable uvloop py3.6 combo in ci

- aioredis/connection.py
asyncio.open_connection requires SSLContext as ssl argument, but RedisSSLContext given. RedisSSLContext has .get() method, which produces SSLContext object. Using this method to provide right argument
> fix ssl argument in _connect method

- codecov.yml
- setup.cfg
Codecov does not pick up on all files, e.g. aioredis/connection.py located at this commit in codecov: https://codecov.io/gh/aio-libs/aioredis-py/tree/b9694797d452bb8d4ca26d2dc14ce73068575130. Resolve via comment in codecov forum: correct fix: https://community.codecov.io/t/codecov-report-missing-files/1928/9 original fix: ~~https://community.codecov.io/t/missing-files-in-codecov-but-not-in-report/825/9~~
> Fix codecov paths

- README.md
- aioredis/sentinel.py
This diff allows to pass ssl=True inside **connection_kwargs for Sentinel class to enable ssl connection to redis
Besides enabling functionality itself this change also makes experience with Sentinel() more consistent with Redis()
Now SentinelManagedConnection enherits from SSLConnection, instead of Connection. 
This allows to populate ssl related properties from SSLConnection class. 
if ssl=True SentinelManagedConnection uses parents constructor (SSLConnection)
If ssl=False SentinelManagedConnection uses grandparents constructor (Connection class)
The only downside of this implementation, is in case ssl=False instance of SentinelManagedConnection has dangling ssl-cert related properties.This properties does not affect behavior in any considerable way.
Afaik there is no obvious way to …
> Allow ssl connection to redis when use sentinel

- CHANGES/951.bugfix
- CONTRIBUTORS.txt
- aioredis/connection.py
setting timeout on asyncio socket leads to an Exception being thrown
This changes remove settimeout call as suggested by @Andrew-Chen-Wang 
No
https://github.com/aio-libs/aioredis-py/issues/951#issuecomment-827322087
> Remove socket timeout setup

- CHANGES/1002.removal
- aioredis/client.py
- aioredis/connection.py
The new 2.0 implementation has a number of places where it either takes an explicit loop parameter, or passes one to an asyncio function. The need for this was largely removed in Python 3.5.3 (because get_event_loop was changed to return the event loop of the current task when called from inside a task), and many functions (such as wait_for deprecated the parameter in 3.8 with removal for 3.10. Other functions (like open_connection) didn't deprecate it, but made it optional and documented that it is not needed when called from a coroutine. I wouldn't be surprised if they are deprecated in future.
Only compared to 2.0.0a1:
1. `__del__` will now always use asyncio.get_event_loop(). But `__del__` is broken anyway, for reasons I've explained in #930.
2. PubSub.run_in_thread is a synchronous …
> Remove unneeded `loop` arguments

- CHANGES/1009.misc
- setup.py
This is a temporary workaround for #1008, due to the type annotations
being wrong. The type annotations should eventually be fixed.
Use of aioredis will not be type-checked when running mypy.
#1008
* Make sure to use full sentences with correct case and punctuation, …
> Remove py.typed

- CHANGES/1016.bugfix
- aioredis/lock.py
Fix aioredis.lock.Lock using a sleep that blocks the event loop.
No.
#1016
> [2.0] Fix aioredis.lock.Lock using a sleep that blocks the event loop

- aioredis/client.py
Avoids an AttributeError from being thrown if in the process of attempting UNWATCH in Pipeline.reset(), the connection is closed and Pipeline.connection is set to None.
No changes.
No known issue (though I could open one).
* Make sure to use full sentences with correct …
> Avoid AttributeError from Pipeline.reset() with a ConnectionError.

- CONTRIBUTORS.txt
- README.md
- aioredis/client.py
- aioredis/connection.py
without the fix this example:
```
my_key: str = "test_1"
async with redis_client.pipeline() as pipe:
await pipe.watch(my_key)
pipe.multi()
await pipe.set(my_key, 0)
await pipe.execute()
```
fails with something like this:
```
....
File "aioredis/client.py", line 879, in initialize
AttributeError: 'Pipeline' object has no attribute 'single_connection_client'
```
The pipeline (pipe) is redis-py's implementation of redis transaction (https://redis.io/topics/transactions).
In terms of aioredis implementation:
`Pipeline `is a child class of `Redis `class
When you try run `pipe.set()` you actually run method from parent (Redis)
inside of this parent's method (pipe.set()) special function `execute_command()` is executed 
This `execute_command()` is overridden in child `Pipeline `and looks …
> add __await__ for Pipeline class

- CHANGES/1008.bugfix
- aioredis/client.py
Fix min, max args of `Z*LEX*` to str
This is still wrong (they can be any encodable value), but it's less
wrong than `int`. Leaving making them less wrong for a more generic
cleanup of annotations (see #1008).
No run-time changes.
#1008
* Make sure to use full …
>  Fix min, max args of Z*LEX* to str

- CHANGES/1008.bugfix
- aioredis/client.py
- aioredis/connection.py
- tests/test_commands.py
- tests/test_encoding.py
There is a lot of cleanup of annotations, mostly to relax them to allow `bytes` where previously only `str` was allowed, but also some fixes for incorrect annotations. Refer to the individual commits for the details.
No, these should be strictly static typing changes. There is still polishing to be done, so I haven't brought back py.typed yet.
#1008 
* `.removal`: Signifying a deprecation or removal of …
> Big batch of type annotation fixes

- CHANGES/1007.feature
- aioredis/client.py
- tests/test_pubsub.py
The port from redis-py brought along PubSub.run_in_thread, and it was
modified to run code on the event loop. However, threading is not the
appropriate concurrency model for aioredis, so I've extracted the logic
and moved it into a `run` coroutine.
Also remove the test that covered run_in_thread and replace it with a
couple of tests for `run`. They're not the strongest tests (just send
and process a single message), but will at least catch simple errors
like missing awaits.
Yes, compared to 2.0.0a1. Code using PubSub.run_in_thread will need to be modified to use PubSub.run.
#1007 
* if you don't have an `issue_id` change it to the pr id after …
> Replace PubSub.run_in_thread with coroutine run

- CHANGES/1009.misc
- setup.py
It was initially removed in #1009, because the type annotations had many
flaws, but a number of PRs have improved that situation.
mypy will now type-check use of aioredis again.
Closes #1008.
* Make sure to use full sentences with correct case and punctuation, for …
> Bring back py.typed

- CHANGES/1003.misc
- aioredis/client.py
- aioredis/connection.py
- aioredis/lock.py
- tests/test_connection_pool.py
- tests/test_lock.py
- tests/test_pubsub.py
This ensures that all timing uses a consistent (and monotonic) clock. This should probably only get merged if a similar redis-py PR (https://github.com/andymccurdy/redis-py/pull/1491) which switches from time.time to time.monotonic is accepted.
Closes #1003.
No, unless they're mocking time, in which case only one source of time needs mocking (I'm hoping this will work with fakeredis + async-solipsism, but haven't test it yet).
#1003
* `.doc`: Signifying …
> Use asyncio event loop to get time

- CHANGES/1060.bugfix
- aioredis/connection.py
- tests/test_connection.py
Adds the parameter `socket_connect_timeout` to
UnixDomainSocketConnection and sets it.
As a subclass of `Connection`, this class's `disconnect()` method
expects a `socket_connect_timeout` property. We now accept that as a
parameter and set it correctly.
fixes #1060
* …
> Set socket_connect_timeout

- CHANGES/1065.bugfix
- aioredis/client.py
Rename the health check, so we aren't also using "redis-py-healthcheck."
Fixes #1065 
> Rename the health check

- CHANGES/1068.bugfix
- aioredis/connection.py
- tests/test_connection_pool.py
> Add _lock to BlockingConnectionPool

- CHANGES/930.misc
- aioredis/__init__.py
- docs/index.md
- setup.py
Bumps the version to 2.0.0 in prep for tagging the release.
Fixes #1031
An unqualified `pip install aioredis` will now install version 2.0.0. This version is not backwards compatible with earlier versions of aioredis. Instead, it aims to port the redis-py API to asyncio.
#930 
* `.misc`: A ticket has been closed, but it is not of interest …
> Bump the version for 2.0.0 release

- CHANGES/1084.bugfix
- docs/requirements.txt
Dependabot upgraded a dependency that doesn't appear to have a security vulnerability, and the other tools in our docs toolchain require the older version. This PR restores the older version.
No.
Fixes #1084 
* Make sure to use full sentences with correct case and …
> Restore mkdocs-autorefs version

- .github/workflows/ci.yml
- .mypy.ini
- CHANGES/1101.misc
- Makefile
- aioredis/client.py
- aioredis/compat.py
- aioredis/connection.py
- aioredis/sentinel.py
- aioredis/utils.py
Initial mypy config and type fixes to get it enabled in CI.
Starting on this while I'm waiting on some other things.
> Enable mypy in CI

- CHANGES/1141.bugfix
- CONTRIBUTORS.txt
- aioredis/client.py
- aioredis/connection.py
Fix the type annotation for `socket_keepalive_options` to follow the standard library's
`socket.Socket.setsockopt()` method.
No behavioral changes but this will fix bogus errors with static type checks.
resolves #1141
* Make sure to use full sentences with correct case …
> Fix typing of socket_keepalive_options to follow stdlib's setsockopt()

- CHANGES/1214.bugfix
- CONTRIBUTORS.txt
- aioredis/client.py
Resolve the restrictive typing on evalsha keys_and_args argument.
No, this change only affects typing hints.
Fix #1214
> Fix typing on evalsha keys_and_args argument

- CHANGES/1212.bugfix
- CONTRIBUTORS.txt
- aioredis/connection.py
- tests/conftest.py
- tests/test_connection.py
Fix issue when the exception is raised on connection initialization in PythonParser
Add parametrization for both parsers to all tests using redis client to catch these errors in the future
No
#1212
#1114
* Make sure to use full sentences with correct case and …
> Fix buffer is closed error when using PythonParser class

- CHANGES/1224.bugfix
- aioredis/client.py
- tests/conftest.py
Improves typing on [blpop](https://redis.io/commands/blpop)'s *timeout* argument, which is a number of seconds (not milliseconds) and allows decimal precision:
> The timeout argument is interpreted as a double value specifying the maximum number of seconds to block. A timeout of zero can be used to block indefinitely.
Other blocking `b*` methods were updated similarly. I also fixed some low-hanging mypy errors under `tests/`.
No change in behavior, only type hint changes.
N/A
* …
> Fix typing on blpop (etc) timeout argument

- CHANGES/1249.bugfix
- CONTRIBUTORS.txt
- aioredis/connection.py
Fixes #1249
It instantiate an `asyncio.Lock` in `UnixDomainSocketConnection.__init__` . This is done to reflect changes that occurred in #1106 .
Commands over Unix socket to Redis now succeed.
#1249
* Make sure to use full sentences with correct case and punctuation, …
> Fix lock is not instantiated on UnixDomainSocketConnection init (#1249)

- .github/workflows/ci.yml
- CHANGES/1256.feature
- aioredis/client.py
- tests/test_connection_pool.py
Signed-off-by: Andrew-Chen-Wang <acwangpython@gmail.com>
Add auto_close_connection_pool for Redis-created connection pools, not manually created pools. Adds close_connection_pool in Redis.close() for manual override on whether to close connection pool or not.
Yes, connection pools automatically disconnect. The user may still disconnect all connections from the connection pools themselves, but it is safe to remove their code for doing so. It is also safe to leave it as is.
Fixes #1103 
* …
> Add auto_close_connection_pool and close_connection_pool in Redis.close()

- CHANGES/1219.misc
- pyproject.toml
- tests/conftest.py
To speed up testing add markers for selecting/deselecting following cases:
* hiredis_parser
* python_parser
* connection pool
* single connection
Following up on #1213 as the current test suite could take longer to run, it makes sense to have more granularity when selecting tests.
It is probably most convenient to use for deselecting tests. For example:
```bash
pytest -k "not python_parser and not connection_pool" -v
```
No changes to behavior
#1213 
* …
> Add test markers to allow more granularity selecting tests

- CHANGES/1284.feature
- CONTRIBUTORS.txt
- aioredis/client.py
- tests/test_pubsub.py
As mentioned in #1235 you can't use coroutines as custom callbacks. This patch tries to fix that.
There shouldn't be any changes for the users as sync callbacks are still supported.
#1235 
* Make sure to use full sentences with correct case and punctuation, for …
> Support for async callbacks
