aio-libs/aioredis-py

- aioredis/util.py
- tests/_testutil.py
- tests/hash_commands_test.py
- tests/string_commands_test.py
> util functions fix (fixes : #70)

- aioredis/commands/__init__.py
- aioredis/commands/cluster.py
- aioredis/commands/hash.py
- aioredis/commands/server.py
- docs/mixins.rst
new cluster commands;
few fixes;
> Commands 3.0

- aioredis/pool.py
- tests/pool_test.py
> fixed pool growth over maxsize

- .travis.yml
Also updated redis server versions
> Update .travis.yml: switch to travis containers

- .travis.yml
- aioredis/commands/generic.py
- aioredis/commands/hash.py
- aioredis/commands/set.py
- aioredis/commands/sorted_set.py
- aioredis/util.py
- tests/generic_commands_test.py
- tests/hash_commands_test.py
- tests/set_commands_test.py
- tests/sorted_set_commands_test.py
Support `async for` in scan commands
> Implement iscan, izscan, isscan, ihscan commands

- .travis.yml
- aioredis/util.py
- tests/pubsub_commands_test.py
Added `Channel.iget()` method.
(travis caching updated as a side effect)
> Async for pubsub Channel

- aioredis/connection.py
> Use NODELAY for tcp sockets

- aioredis/connection.py
- tests/pubsub_commands_test.py
> Pubsub concurrency fix

- aioredis/commands/server.py
> remove invalid uses of next()

- aioredis/__init__.py
- aioredis/abc.py
- aioredis/connection.py
- aioredis/pubsub.py
- aioredis/util.py
- tests/pool_test.py
- tests/pubsub_listener_test.py
Also cherry-picked `abc` module from sentinel wip;
> Multi-producers, single-consumer pub/sub queue

- aioredis/__init__.py
- aioredis/commands/__init__.py
- aioredis/commands/geo.py
- docs/mixins.rst
- docs/spelling_wordlist.txt
- tests/geo_commands_test.py
> Few enhancements to Geo commands

- .appveyor.yml
- .travis.yml
- README.rst
- tests/conftest.py
- tests/connection_commands_test.py
- tests/connection_test.py
- tests/generic_commands_test.py
- tests/pool_test.py
- tests/pubsub_listener_test.py
- tests/server_commands_test.py
- tests/string_commands_test.py
Enable tests on windows through Appveyor service.
However only single redis server version is tested.
> Appveyor integration

- docs/examples.rst
- examples/commands.py
- examples/connection.py
- examples/pool.py
- examples/pubsub.py
- examples/py34/pool.py
- examples/scan.py
- examples/sentinel.py
- examples/transaction.py
add sentinel client example; updated other examples
> examples update

- README.rst
- aioredis/commands/__init__.py
- aioredis/connection.py
- aioredis/pool.py
- aioredis/sentinel/pool.py
- docs/api_reference.rst
- docs/index.rst
Allow to set custom protocol reader class.
> Add `parser` argument

- .travis.yml
- Makefile
- aioredis/commands/server.py
- tests/server_commands_test.py
* allow PyPy build to fail — its so unstable on travis
* more tests for server commands
* implement `command*` commands
> Commands enhancement

- .travis.yml
- Makefile
- README.rst
- aioredis/commands/generic.py
- aioredis/commands/hash.py
- aioredis/commands/set.py
- aioredis/commands/sorted_set.py
- aioredis/pool.py
- aioredis/pubsub.py
- aioredis/util.py
- docs/index.rst
- setup.py
- tests/conftest.py
Fixes #304.
Also drop < Python 3.5.3.
> Drop support for Python 3.3 and 3.4

- README.rst
- aioredis/connection.py
- aioredis/pool.py
- aioredis/util.py
- docs/api_reference.rst
- docs/spelling_wordlist.txt
- docs/start.rst
- examples/commands.py
- examples/connection.py
- examples/iscan.py
- examples/pipeline.py
- examples/pool.py
- examples/pool2.py
- examples/pool_pubsub.py
- examples/pubsub.py
- examples/pubsub2.py
- examples/scan.py
- examples/transaction.py
- examples/transaction2.py
- tests/conftest.py
- tests/connection_test.py
- tests/parse_url_test.py
> Url parser

- aioredis/sentinel/commands.py
- aioredis/sentinel/pool.py
> update sentinel client to use async/await syntax

- aioredis/connection.py
- aioredis/util.py
- tests/encode_command_test.py
- tests/string_commands_test.py
I have not actually run the tests myself as there is no documentation on how to do so (#328). But I believe these changes are sufficient to fix the issue.
> Support passing bytearray to Redis commands (closes #324)

- aioredis/commands/server.py
Also, docstring has been updated
> Added async support for flushall() and flushdb()

- aioredis/commands/__init__.py
- aioredis/commands/generic.py
- aioredis/commands/server.py
- aioredis/commands/string.py
- tests/connection_commands_test.py
- tests/generic_commands_test.py
Added commands:
will leave just as stubs for now:
> Add several missing commands

- aioredis/sentinel/pool.py
- tests/conftest.py
- tests/sentinel_commands_test.py
- tests/sentinel_failover_test.py
> Fix SentinelPool.discover_timeout usage

- aioredis/commands/generic.py
- aioredis/commands/list.py
- aioredis/commands/server.py
- aioredis/commands/sorted_set.py
- aioredis/commands/string.py
- docs/api_reference.rst
Fix typos in documentation and error messages.
> Typo fixes

- aioredis/commands/set.py
- tests/set_commands_test.py
> add a count to spop

- tests/pubsub_commands_test.py
> add a test to check pub/sub channel disconnect

- aioredis/commands/streams.py
- tests/stream_commands_test.py
> Add MKSTREAM option to XGROUP CREATE command

- aioredis/errors.py
- tests/stream_commands_test.py
> Add a BUSYGROUP reply error

- CONTRIBUTORS.txt
- tests/conftest.py
* Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`
> completed task 'Update tests runner to lookup host's redis-server'

- CONTRIBUTORS.txt
- aioredis/commands/generic.py
- aioredis/commands/server.py
- tests/generic_commands_test.py
* generic.py -> passed encoding='utf-8' parameter to command, delete TODO
* server.py -> changed host argument to default, delete unused import and conditional statement with logger.warning
Cleanup code from TODOs
* Make sure to use full sentences with correct case …
> Cleanup TODOs (#578)

- CONTRIBUTORS.txt
- aioredis/commands/streams.py
- tests/stream_commands_test.py
Added non-integer checking in xread
#567 
* Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`
> Added non-integer checking

- README.rst
- docs/index.rst
Just documentation fixes. Also made README.rst and index.rst more similar.
No.
> Small documentation fixes

- CHANGES/438.feature
- CONTRIBUTORS.txt
- aioredis/commands/streams.py
- tests/stream_commands_test.py
Added xdel and xtrim method which missed in commands/streams.py.
And Also added unit test code of them.
I don't think so, it is just additional methods missed.
438
[https://github.com/aio-libs/aioredis/issues/438](https://github.com/aio-libs/aioredis/issues/438)
* …
> Add xdel and xtrim

- CHANGES/612.misc
- Makefile
- aioredis/locks.py
- docs/requirements.txt
- tests/pool_test.py
Some minor improvements in tests
> Test fixes

- CHANGES/619.misc
- docs/requirements.txt
- setup.cfg
- tests/pool_test.py
- tests/requirements-mypy.txt
- tests/requirements.txt
> Dependencies update

- .travis.yml
- CHANGES/620.misc
- Makefile
- tests/stream_commands_test.py
> Travis ci updates

- .travis.yml
- CHANGES/643.misc
- Makefile
- docs/devel.rst
- tests/_testutils.py
- tests/conftest.py
- tests/generic_commands_test.py
- tests/pool_test.py
- tests/pubsub_commands_test.py
- tests/pubsub_receiver_test.py
- tests/sentinel_commands_test.py
- tests/sentinel_failover_test.py
- tests/server_commands_test.py
- tests/stream_commands_test.py
Slightly improve tests running time
> Slightly improve tests execution time

- CONTRIBUTORS.txt
- setup.py
setup.py keeps falling in Travis because of black reformat
Also, thanks for revamping aioredis!
no
> Prevent setup.py from failing to get version

- CONTRIBUTORS.txt
- aioredis/connection.py
I forked the repo today to submit a pr for another issue but it had syntax issues, which i think got introduced due to the recent format changes. I have added the deleted lines back after referencing the second to last commit and pytest also passes.
No
None
* Make …
> Fix syntax error introduced from code reformat

- CHANGES/850.misc
- docs/devel.rst
Add pip install -e . to developer instructions. This is needed for pytest to find the tests.
No.
Closes #850.
These are mostly N/A:
`Fix issue with non-ascii contents in doctest text …
> Add pip install -e . to developer instructions

- CHANGES/655.doc
- CONTRIBUTORS.txt
- docs/examples.rst
- examples/blocking.py
Add an example of using blocking commands to the documentation.
#511
> add example of using blocking commands

- README.rst
> Drop 35 from readme

- tests/conftest.py
> Correct a typo in conftest.py

- aioredis/__init__.py
Bump the version to 2.0.0 alpha release 1.
> Bump version to 2.0.0a1 for an alpha release

- aioredis/client.py
- aioredis/connection.py
f-strings instead of %s string interpolation are supported in Python 3.6+ and are faster.
> Use f-strings for performance

- codecov.yml
- setup.cfg
Supersedes #956 to resolve the comments about how you couldn't actually view the files...
Final solution comes from: https://github.com/thomasrockhu/aioredis-py/pull/1
> Fix codecov folder structure

- aioredis/connection.py
Fixes unix domain sockets in aioredis -- there were a couple issues that seemed to break them entirely.
No changes other than unix domain sockets (seem to) work now.
None, though I could open one if desired! Also, ideally there would be a unit test for unix domain socket connections.
* `.misc`: A ticket has been closed, but it is not of …
> Fix UnixDomainSocketConnection

- aioredis/connection.py
> Variable shadows import

- CHANGES/1043.bugfix
- MANIFEST.in
otherwise installation from the source distribution fails, as setup.py
tries to read CHANGELOG.md which wasn't there
No
> include CHANGELOG.md in the sdist

- aioredis/client.py
Arguments specified as `Mapping[KeyT, EncodableT]` or similar were
problematic because Mapping is no covariant on the key type, which means
that passing a `Dict[KeyT, str]` would work fine, but a `Dict[str, str]`
would not because str != KeyT.
Instead of using a union, use a TypeVar for Mapping key types. This
causes the type checker to infer the actual key type, which must be one
of the types listed. So now `Dict[str, str]` will work, although, say,
`Dict[Union[str, bytes], str]` will not. That could potentially be
improved by defining a Protocol that is similar to Mapping (possibly a
subset that only allows iteration, not lookups), but there are
diminishing returns since I assume most callers will pass either str or
bytes but not a mix.
No, type annotation changes only.
See #1008.
* The …
> Improve type annotations for Mapping arguments

- aioredis/lock.py
Allow `name` argument to Lock to be bytes.
See #1008
No new CHANGES file because it's covered by the existing one for #1008.
> Allow `name` argument to Lock to be bytes

- docs/examples/blocking.py
Update the blocking commands example to use `async with`.
No.
#998 
> Use "async with" instead of "with await"

- docs/index.md
Shows proper installation instructions for the alpha version of aioredis which pypi doesn't default install.
Yes
#930 
Specifically https://github.com/aio-libs/aioredis-py/issues/930#issuecomment-835443521
* Make sure to use full sentences with correct case and …
> Add proper installation instructions in docs

- CHANGES/1036.feature
- aioredis/client.py
Commit: https://github.com/andymccurdy/redis-py/commit/bc5854217b4e94eb7a33e3da5738858a17135ca5
Updates with redis-py commit https://github.com/andymccurdy/redis-py/commit/bc5854217b4e94eb7a33e3da5738858a17135ca5
No
* Make sure to use full sentences with correct case …
> Update with redis-py/bc58542

- CHANGES/1037.feature
- aioredis/lock.py
Update with redis-py commit https://github.com/andymccurdy/redis-py/commit/c7e26ae6749f63b9ebf65c023f270b2ea2b9536a
No
None
> Update with redis-py/c7e26ae

- .github/workflows/ci.yml
- CHANGES/1045.bugfix
- tests/test_commands.py
Use Redis 6.2.4. in CI.
No.
Relates to #930.
> Use redis 6.2.4 in CI

- CHANGES/1083.bugfix
- CONTRIBUTORS.txt
- aioredis/client.py
- aioredis/connection.py
- aioredis/lock.py
Fix type annotations: added `typing.Optional` for values with default `None`
This fix adds ability to use correct type checking (e.g. mypy support)
Fixes: #1083 
`Fix issue with non-ascii …
> Fix optional types

- docs/getting-started.md
Fix typo in Getting Started page
no
-
-----
[View rendered docs/getting-started.md](https://github.com/c-h3xcode/aioredis-py/blob/patch-2/docs/getting-started.md)
> Fix typo in Getting Started

- docs/migration.md
Fix typo in Migration page
No
-
-----
[View rendered docs/migration.md](https://github.com/dmitrylink/aioredis-py/blob/master/docs/migration.md)
> Fix typo in Migration page

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- CHANGES/1080.feature
- CONTRIBUTORS.txt
Introduce [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)
The new issue forms will allow contributors to include specific, structured information.
* `.misc`: A ticket has been closed, but it is not of …
> Introduce issue forms

- CHANGES/1095.misc
- setup.py
Fix url because the repository name changed.
No.
N/A.
> Update url for repository rename in setup.py

- CHANGES/1109.doc
- docs/changelog.md
- docs/migration.md
Document 2 breaking changes in API.
Nope.
None.
-----
[View rendered …
> [Doc] Document some breaking changes about the API

- CHANGELOG.md
- CHANGES/1247.misc
- README.md
- aioredis/__init__.py
-----
[View rendered CHANGELOG.md](https://github.com/aio-libs/aioredis-py/blob/new-version/CHANGELOG.md)
[View rendered …
> Release version 2.0.1

- CHANGES/1302.misc
- README.md
Migrating to redis-py README update :)
-----
[View rendered README.md](https://github.com/aio-libs/aioredis-py/blob/Andrew-Chen-Wang-patch-1/README.md)
> Update README regarding migration
